### PR TITLE
Used as value inspection (fixes #1887)

### LINKED ISSUE #1887: a = b used as value
As an extension of #1577.

```go
package main

func main() {
	a := 1
	b := 2
	if a = b {  // should produce an error: a = b used as value
		println("a = b")
	} else {
		println("a != b")
	}
}
```

### PR DESCRIPTION
**Pull request by dlsniper**

### CODE REVIEW

**Comment by dlsniper** [comment]
I've finished with this PR but for some reason the test fails and when running inside the IDE using the same file, the inspection(s) work correctly.

**Comment by dlsniper** [comment]
I've updated this to also contain a test for the quick fix and everything works fine now from the tests. Please let me know if it's missing anything before it can be merged. Thank you.

**Comment by dlsniper** [comment]
Rebased as well (all should be green now)

File: testData/highlighting/equalinif.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
+package equalinif
+
+func <warning descr="Unused function 'eqlfunc'">eqlfunc</warning>() {
```
Comment (zolotov) [inline testData/highlighting/equalinif.go]: use _ name in order to avoid redundant inspection reports

File: src/com/goide/inspections/GoUsedAsValueInCondition.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+          String left = StringUtil.join(o.getVarDefinitionList(), GET_TEXT_FUNCTION, ", ");
+          String right = StringUtil.join(o.getExpressionList(), GET_TEXT_FUNCTION, ", ");
+
+          holder.registerProblem(o, left + " := " + right + " used as value", GENERIC_ERROR_OR_WARNING, new GoAssignmentToComparisonQuickFix(o));
+        }
+      }
+    };
+  }
+
+  public static class GoAssignmentToComparisonQuickFix extends LocalQuickFixOnPsiElement {
```
Comment (zolotov) [inline src/com/goide/inspections/GoUsedAsValueInCondition.java]: You don't need LocalQuickFixOnPsiElement because this fix is used in inspection only and it the same element in inspection report and in quick with. Please reimplement with LocalQuickFix.

Also I think it shouldn't be public

File: testData/highlighting/equalinif.go (hunk 1 above)
Comment (dlsniper) [inline testData/highlighting/equalinif.go]: Can you please give me an example? I'm not sure I understand what do you mean. Thank you.

File: src/com/goide/inspections/GoUsedAsValueInCondition.java (hunk 2 above)
Comment (dlsniper) [inline src/com/goide/inspections/GoUsedAsValueInCondition.java]: Done.

File: testData/highlighting/equalinif.go (hunk 1 above)
Comment (ignatov) [inline testData/highlighting/equalinif.go]: Just replace `<warning descr="Unused function 'eqlfunc'">eqlfunc</warning>` in your test data with `_`. There're lots of examples around, please have a look.

Comment (dlsniper) [inline testData/highlighting/equalinif.go]: Ah, I thought I need to do something like `<warning descr="_">eqlfunc</warning>`. Done this as well. Thank you.
